# Generated by Django 4.0.6 on 2022-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_contact', models.BigIntegerField()),
                ('emp_email', models.EmailField(max_length=50)),
            ],
        ),
    ]
